### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by phongXEM** [pticon91/directus-extensions-dcb-tree-view-bundle#5]
filter is not working. I filter type is product but results incorrect
<img width="883" alt="Screenshot at Sep 27 09-26-00" src="https://github.com/user-attachments/assets/ff77e87b-855c-4a61-b03e-80182f334e65">

**Comment by digital-cowboy-91** [comment]
duplicate of https://github.com/digital-cowboy-91/directus-extensions-dcb-tree-view-bundle/issues/4
